apiVersion: v1
kind: Pod
metadata:
  name: shell-exec
  namespace: learning-command-args
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: command-env-lab:0.1
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c"]
    args: ["exec sleep 3600"]
