apiVersion: v1
kind: Pod
metadata:
  name: args-only
  namespace: learning-command-args
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: command-env-lab:0.1
    imagePullPolicy: IfNotPresent
    args: ["9090"]
