apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume
  namespace: learning-configmap
spec:
  containers:
    - name: reader
      image: alpine:3.20
      command: ["sleep", "3600"]
      volumeMounts:
        - name: config
          mountPath: /config/live
        - name: config
          mountPath: /config/frozen/application.conf
          subPath: application.conf
  volumes:
    - name: config
      configMap:
        name: file-config
  restartPolicy: Never
